1-module
js-tasks-ru/jsbasic-20210906-2_julia7 pull request #2
Opened 2021-08-30 16:07 UTC by jakiJ

1-task +
2-task +
3-task +
4-task +
5-task +

2021-08-30 16:08 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-06 19:12 UTC, SinimaWath requested changes

2021-09-06 19:12 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
Давай попробуем упростить:
- уменьшения вложенности через https://refactoring.guru/ru/replace-nested-conditional-with-guard-clause

2021-09-06 19:12 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return boo;
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`returntypeof name == 'string' ....`

Это как раз тот случай

2021-09-06 19:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let low = str.toLowerCase()
Если переменная не изменяется, то это **const**

2021-09-06 19:12 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return low.includes('1xbet') || low.includes('xxx') || false
|| false - тут лишняя. 

Операция `low.includes('1xbet') || low.includes('xxx')` - и так возвращает boolean, так как оба операнда boolean

2021-09-06 19:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-06 19:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-08 11:30 UTC, jakiJ commented on 1-module/1-task/index.js
> +  }
ссылка 404

2021-09-08 11:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-08 11:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-09 10:32 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
https://refactoring.guru/ru/replace-nested-conditional-with-guard-clauses

2021-09-09 20:22 UTC, SinimaWath approved these changes

2021-09-09 20:22 UTC, merged