2-module
js-tasks-ru/jsbasic-20210906-2_julia7 pull request #3
Opened 2021-09-13 16:26 UTC by jakiJ

2021-09-13 16:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-13 19:44 UTC, SinimaWath requested changes

2021-09-13 19:44 UTC, SinimaWath commented on 2-module/1-task/index.js
> +      if(salaries[item] > 0 && salaries[item] < Infinity && typeof salaries[item] == 'number') {
Хорошее решение. Но для проверки на NaN, Infinity, -Infinity - есть более подходящие: `isFinite` - давай его заиспользуем

 https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/isFinite

2021-09-14 12:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-14 12:51 UTC, jakiJ commented on 2-module/1-task/index.js
> +      if(salaries[item] > 0 && salaries[item] < Infinity && typeof salaries[item] == 'number') {
использовала  isFinite, спасибо за совет

2021-09-14 19:41 UTC, SinimaWath requested changes

2021-09-14 19:41 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  }, [])
Немного сложно, давай использовать тут map, он болше подходит

2021-09-14 19:41 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return arr.filter(item => item !== '-').join('')
Это можно упростить, до split().map().join().

Давай подумаем как

2021-09-14 19:41 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return res.join('\n')
Это filter->map->join

2021-09-15 09:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-15 09:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-15 10:01 UTC, jakiJ commented on 3-module/3-task/index.js
> +  return arr.filter(item => item !== '-').join('')
не понимаю, как задать условие в мап чтобы проверять пробел перед словом

2021-09-15 19:27 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return arr.filter(item => item !== '-').join('')
 `map((word, index) => index === 0 ? ... : ...)` - примерно вот так, тебе достаточно в данной задачи условия на index === 0

2021-09-16 10:58 UTC, jakiJ commented on 3-module/3-task/index.js
> +  return arr.filter(item => item !== '-').join('')
точно, спасибо!

2021-09-16 10:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-16 20:05 UTC, SinimaWath approved these changes
все круто!

2021-09-16 20:05 UTC, merged